version: '3.1'

services:
  postgresql:
    container_name: postgresql
    restart: always
    image: postgres:12.1
    environment:
      - POSTGRES_USER=groov
      - POSTGRES_PASSWORD=groov
      - POSTGRES_DB=groov
    ports:
      - '5433:5432'

  graphql:
    container_name: graphql
    restart: always
    build: ./packages/graphql
    ports:
      - '3000:3000'
    depends_on:
      - postgresql
