version: '3.1'

services:
  postgresql:
    container_name: postgresql
    restart: always
    build: ./packages/postgresql
    environment:
      - POSTGRES_USER=groov
      - POSTGRES_PASSWORD=groov
      - POSTGRES_DB=groov
    ports:
      - '5432:5432'

  migration:
    container_name: migration
    build: ./packages/migration 
    links:
      - postgresql
    depends_on:
      - postgresql

  graphql:
    container_name: graphql
    restart: always
    build: ./packages/graphql
    environment:
      - DATABASE_URL=postgresql
      - DATABASE_USER=groov
      - DATABASE_PASSWORD=groov
      - DATABASE_DB=groov
    ports:
      - '3000:3000'
    depends_on:
      - postgresql

# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es02,es03
      # - cluster.initial_master_nodes=es01,es02,es03
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    # networks:
    #   - elastic

  # es02:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
  #   container_name: es02
  #   environment:
  #     - node.name=es02
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es03
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data02:/usr/share/elasticsearch/data
  #   networks:
  #     - elastic

volumes:
  data01:
    driver: local
  # data02:
  #   driver: local
  # data03:
  #   driver: local

# networks:
#   elastic:
#     driver: bridge