version: '3.1'

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:12.1
    environment:
      - POSTGRES_USER=groov
      - POSTGRES_PASSWORD=groov
      - POSTGRES_DB=groov
    ports:
      - '5432:5432'
