version: "3.1"

services:
  postgresql:
    container_name: postgresql
    restart: always
    build: ./packages/postgresql
    environment:
      - POSTGRES_USER=groov
      - POSTGRES_PASSWORD=groov
      - POSTGRES_DB=groov
    ports:
      - "5432:5432"

  migration:
    container_name: migration
    build:
      context: ./packages/migration
      dockerfile: Dockerfile.dev
    links:
      - postgresql
    environment:
      - DATABASE_USER=groov
      - DATABASE_PASSWORD=groov
      - DATABASE_DB=groov
      - DATABASE_HOST=postgresql
      - ELASTICSEARCH_HOST=es01
    depends_on:
      # - es01
      - postgresql
      - graphql

  graphql:
    container_name: graphql
    restart: always
    build:
      context: ./packages/graphql
      dockerfile: Dockerfile.dev
    environment:
      - BUILD_VARIANT=development
      - DATABASE_URL=postgresql
      - DATABASE_USER=groov
      - DATABASE_PASSWORD=groov
      - DATABASE_DB=groov
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=5432"
      - GOOGLE_APPLICATION_CREDENTIALS=secrets/dev/groov-development-ddc9d-firebase-adminsdk-9rr20-ced53ec6f8.json
    ports:
      - "3001:3001"
    depends_on:
      - postgresql
    volumes:
      - server:/usr/share/server/data

  # web:
  #   container_name: web
  #   restart: always
  #   build:
  #     context: ./packages/web
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - graphql
  #   depends_on:
  #     - postgresql
  #     - graphql
  #     - migration
  #     # - es01
  #   volumes:
  #     - "./packages/web:/web"
  #     - "/web/node_modules"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  # https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docker.html
  # es01:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
  #   container_name: es01
  #   environment:
  #     - node.name=es01
  #     - cluster.name=es-docker-cluster
  #     # - discovery.seed_hosts=es02,es03
  #     # - cluster.initial_master_nodes=es01,es02,es03
  #     #  es 7+ setting below
  #     # - cluster.initial_master_nodes=es01
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data01:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   command: ["elasticsearch", "-Elogger.level=ERROR"]
  #   # networks:
  #   #   - elastic

  # es02:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
  #   container_name: es02
  #   environment:
  #     - node.name=es02
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es03
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data02:/usr/share/elasticsearch/data
  #   networks:
  #     - elastic

volumes:
  front:
    driver: local
  data01:
    driver: local
  server:
    driver: local
  # data02:
  #   driver: local
  # data03:
  #   driver: local
# networks:
#   elastic:
#     driver: bridge
