apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
        app: groov
        tier: frontend
  template:
    metadata:
      labels:
        app: groov
        tier: frontend
    spec:
      containers:
      - name: web-app
        image: gcr.io/groov-development-ddc9d/groov-web
        imagePullPolicy: Always
        ports:
          - containerPort: 80
    restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
    name: frontend
    labels:
    app: groov
    tier: frontend
spec:
    type: LoadBalancer
    ports:
    # the port that this service should serve on
    - port: 80
    selector:
    app: groov
    tier: frontend