apiVersion: apps/v1
kind: Deployment
metadata:
  name: wavy-frontend
  labels:
    app: wavy
    role: leader
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wavy
      tier: frontend
  template:
    metadata:
      labels:
        app: wavy
        role: leader
        tier: frontend
    spec:
      initContainers:
        - name: wait-for-backend-public
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup wavy-backend-public; do echo waiting for wavy-backend-public; sleep 2; done;",
            ]
      containers:
        - name: web-app
          image: gcr.io/wavy-development/wavy-web:latest
          env:
            # determines how this service gets the hostnames of other services
            - name: GET_HOSTS_FROM
              value: "dns"
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: wavy-frontend
  labels:
    app: wavy
    role: leader
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on, shoudl this be 3000? targetPort: 3000 as well?
    - port: 80
  selector:
    app: wavy
    role: leader
    tier: frontend
