apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: gcr.io/wavy-development/wavy-migration:latest
          env:
            - name: DATABASE_USER
              value: wavy
            - name: DATABASE_PASSWORD
              value: wavy
            - name: DATABASE_DB
              value: wavy
            - name: DATABASE_HOST
              value: "wavy-backend-private"
            - name: ELASTICSEARCH_HOST
              value: "wavy-backend-private"
