apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: gcr.io/groov-development-ddc9d/groov-migration:latest
          env:
            - name: DATABASE_USER
              value: groov
            - name: DATABASE_PASSWORD
              value: groov
            - name: DATABASE_DB
              value: groov
            - name: DATABASE_HOST
              value: "groov-backend"
            - name: ELASTICSEARCH_HOST
              value: "groov-backend"
